export const headerLang = {
  fa: {
    home:        'خانه',
    products:    'محصولات',
    brands:      'برندها',
    about:       'درباره',
    contact:     'تماس',
    search:      'جستجو',
    cart:        'سبد خرید',
    favorites:   'علاقه‌مندی‌ها',
    compare:     'مقایسه',
    toggleTheme: 'تغییر تم',
    toggleLang:  'تغییر زبان',
  },
  en: {
    home:        'Home',
    products:    'Products',
    brands:      'Brands',
    about:       'About',
    contact:     'Contact',
    search:      'Search',
    cart:        'Cart',
    favorites:   'Favorites',
    compare:     'Compare',
    toggleTheme: 'Toggle theme',
    toggleLang:  'Switch language',
  },
};