export const productsLang = {
  fa: {
    pageTitle:      'فروشگاه گوشی',
    heroTitle:      'گوشی بعدی‌ات اینجاست',
    heroSubtitle:   'جدیدترین پرچم‌داران و میان‌رده‌ها، با قیمت رقابتی و ضمانت اصالت.',
    heroCta:        'مشاهده فروشگاه',
    allProducts:    'همه محصولات',
    featured:       'محصولات ویژه',
    filters:        'فیلترها',
    filterBrand:    'برند',
    filterAll:      'همه',
    sortLabel:      'مرتب‌سازی',
    sortNewest:     'جدیدترین',
    sortPriceAsc:   'ارزان‌ترین',
    sortPriceDesc:  'گران‌ترین',
    count:          '{n} محصول',
    loadMore:       'نمایش بیشتر',
    noResults:      'محصولی یافت نشد',
    noResultsHint:  'فیلترها را تغییر دهید یا بعداً سر بزنید.',
    errorLoading:   'خطا در بارگذاری محصولات',
    retry:          'تلاش مجدد',
  },
  en: {
    pageTitle:      'Phone Store',
    heroTitle:      'Your next phone is here',
    heroSubtitle:   'The latest flagships and mid-rangers, at competitive prices, guaranteed authentic.',
    heroCta:        'Browse the store',
    allProducts:    'All products',
    featured:       'Featured products',
    filters:        'Filters',
    filterBrand:    'Brand',
    filterAll:      'All',
    sortLabel:      'Sort',
    sortNewest:     'Newest',
    sortPriceAsc:   'Price: low to high',
    sortPriceDesc:  'Price: high to low',
    count:          '{n} products',
    loadMore:       'Load more',
    noResults:      'No products found',
    noResultsHint:  'Try different filters or check back later.',
    errorLoading:   'Failed to load products',
    retry:          'Retry',
  },
};