export const quickViewLang = {
  fa: {
    btn:           'نمای سریع',
    close:         'بستن',
    addToCart:     'افزودن به سبد',
    outOfStock:    'ناموجود',
    inStock:       'موجود',
    lowStock:      'تنها {n} عدد',
    viewFull:      'مشاهده کامل',
    specs:         'مشخصات خلاصه',
    loading:       'در حال بارگذاری...',
    errorLoad:     'خطا در بارگذاری',
    galleryPrev:   'قبلی',
    galleryNext:   'بعدی',
    discount:      '{n}٪ تخفیف',
    added:         'به سبد اضافه شد',
  },
  en: {
    btn:           'Quick view',
    close:         'Close',
    addToCart:     'Add to cart',
    outOfStock:    'Out of stock',
    inStock:       'In stock',
    lowStock:      'Only {n} left',
    viewFull:      'View full details',
    specs:         'Quick specs',
    loading:       'Loading...',
    errorLoad:     'Failed to load',
    galleryPrev:   'Previous',
    galleryNext:   'Next',
    discount:      '{n}% off',
    added:         'Added to cart',
  },
};