export const contactLang = {
  fa: {
    // Hero
    heroTitle:    'با ما در تماس باش',
    heroSubtitle: 'سوال، پیشنهاد یا انتقادی داری؟ خوشحال می‌شویم بشنویم.',

    // Info cards
    phoneLabel:   'تلفن پشتیبانی',
    phoneValue:   '۰۲۱-۹۱۰۰۰۰۰۰',
    phoneHint:    'شنبه تا پنجشنبه، ۹ صبح تا ۹ شب',
    emailLabel:   'ایمیل',
    emailValue:   'hello@phonestore.ir',
    emailHint:    'پاسخ در کمتر از ۲۴ ساعت',
    addressLabel: 'آدرس',
    addressValue: 'تهران، خیابان ولیعصر، پلاک ۱۲۳',
    addressHint:  'طبقه سوم، واحد ۵',
    socialLabel:  'شبکه‌های اجتماعی',
    socialValue:  '@phonestore',
    socialHint:   'ما را دنبال کنید',

    // Form
    formTitle:    'ارسال پیام',
    formSubtitle: 'فرم زیر را پر کن، در اولین فرصت پاسخ می‌دهیم.',
    name:         'نام و نام خانوادگی',
    namePlaceholder: 'مثلاً: علی محمدی',
    email:        'ایمیل',
    emailPlaceholder: 'you@example.com',
    phone:        'شماره تماس (اختیاری)',
    phonePlaceholder: '۰۹۱۲۳۴۵۶۷۸۹',
    subject:      'موضوع',
    subjectPlaceholder: 'موضوع پیام را انتخاب کنید',
    subjectGeneral: 'سوال عمومی',
    subjectOrder:   'درباره سفارش',
    subjectProduct: 'درباره محصول',
    subjectReturn:  'مرجوعی یا گارانتی',
    subjectOther:   'سایر',
    message:      'متن پیام',
    messagePlaceholder: 'پیام خود را اینجا بنویسید...',
    send:         'ارسال پیام',
    sending:      'در حال ارسال...',

    // Validation
    errName:      'لطفاً نام خود را وارد کنید.',
    errNameShort: 'نام باید حداقل ۳ حرف باشد.',
    errEmail:     'لطفاً ایمیل خود را وارد کنید.',
    errEmailInvalid: 'ایمیل معتبر نیست.',
    errSubject:   'لطفاً موضوع را انتخاب کنید.',
    errMessage:   'لطفاً متن پیام را وارد کنید.',
    errMessageShort: 'پیام باید حداقل ۱۰ حرف باشد.',
    errPhone:     'شماره تماس معتبر نیست.',

    // Success
    successTitle: 'پیام شما ارسال شد',
    successText:  'به‌زودی با شما تماس می‌گیریم. ممنون از پیامت!',
    sendAnother:  'ارسال پیام جدید',

    // FAQ
    faqTitle:     'سوالات پرتکرار',
    faqSubtitle:  'شاید پاسخ سوال تو اینجا باشد.',
    faq1Q:        'چطور سفارشم را پیگیری کنم؟',
    faq1A:        'پس از ثبت سفارش، کد پیگیری از طریق پیامک برایتان ارسال می‌شود. با آن کد می‌توانید وضعیت سفارش را در پنل کاربری مشاهده کنید.',
    faq2Q:        'گارانتی محصولات چطور است؟',
    faq2A:        'همه محصولات ما دارای ۱۸ ماه گارانتی رسمی شرکتی هستند. در صورت بروز مشکل، کافی است با پشتیبانی تماس بگیرید.',
    faq3Q:        'امکان مرجوعی وجود دارد؟',
    faq3A:        'بله، تا ۷ روز پس از دریافت، در صورت سالم بودن کالا و بسته‌بندی، امکان مرجوعی بدون قید و شرط وجود دارد.',
    faq4Q:        'هزینه ارسال چقدر است؟',
    faq4A:        'برای خریدهای بالای ۵ میلیون تومان، ارسال رایگان است. برای سایر سفارش‌ها، هزینه ارسال بر اساس شهر محاسبه می‌شود.',
    faq5Q:        'امکان پرداخت در محل هست؟',
    faq5A:        'در حال حاضر پرداخت آنلاین است. به‌زودی پرداخت در محل برای تهران فعال خواهد شد.',

    // Misc
    orContactUs:  'یا از راه‌های زیر با ما در تماس باش',
  },

  en: {
    heroTitle:    'Get in touch',
    heroSubtitle: 'Got a question, suggestion, or feedback? We\'d love to hear from you.',

    phoneLabel:   'Support phone',
    phoneValue:   '+98 21 9100 0000',
    phoneHint:    'Sat–Thu, 9 AM to 9 PM',
    emailLabel:   'Email',
    emailValue:   'hello@phonestore.ir',
    emailHint:    'Reply within 24 hours',
    addressLabel: 'Address',
    addressValue: '123 Valiasr St, Tehran',
    addressHint:  '3rd floor, unit 5',
    socialLabel:  'Social media',
    socialValue:  '@phonestore',
    socialHint:   'Follow us',

    formTitle:    'Send a message',
    formSubtitle: 'Fill out the form below and we\'ll get back to you shortly.',
    name:         'Full name',
    namePlaceholder: 'e.g., Ali Mohammadi',
    email:        'Email',
    emailPlaceholder: 'you@example.com',
    phone:        'Phone number (optional)',
    phonePlaceholder: '+98 912 345 6789',
    subject:      'Subject',
    subjectPlaceholder: 'Choose a subject',
    subjectGeneral: 'General question',
    subjectOrder:   'About an order',
    subjectProduct: 'About a product',
    subjectReturn:  'Return or warranty',
    subjectOther:   'Other',
    message:      'Message',
    messagePlaceholder: 'Write your message here...',
    send:         'Send message',
    sending:      'Sending...',

    errName:      'Please enter your name.',
    errNameShort: 'Name must be at least 3 characters.',
    errEmail:     'Please enter your email.',
    errEmailInvalid: 'Email is not valid.',
    errSubject:   'Please choose a subject.',
    errMessage:   'Please write your message.',
    errMessageShort: 'Message must be at least 10 characters.',
    errPhone:     'Phone number is not valid.',

    successTitle: 'Message sent',
    successText:  'We\'ll get back to you soon. Thanks for reaching out!',
    sendAnother:  'Send another message',

    faqTitle:     'Frequently asked questions',
    faqSubtitle:  'Your answer might be here.',
    faq1Q:        'How do I track my order?',
    faq1A:        'After placing your order, a tracking code is sent to you via SMS. Use it to check your order status in your account.',
    faq2Q:        'What about product warranty?',
    faq2A:        'All our products come with an 18-month official manufacturer warranty. If you have any issues, just contact support.',
    faq3Q:        'Can I return a product?',
    faq3A:        'Yes, within 7 days of delivery, as long as the product and packaging are in good condition, you can return it — no questions asked.',
    faq4Q:        'How much is shipping?',
    faq4A:        'Orders over 5M IRR ship free. For other orders, shipping cost depends on your city.',
    faq5Q:        'Do you offer cash on delivery?',
    faq5A:        'Currently, we accept online payments. Cash on delivery will be available soon in Tehran.',

    orContactUs:  'Or reach us through the channels below',
  },
};