export const adminLang = {
  fa: {
    // Sidebar
    panel:          'پنل مدیریت',
    dashboard:      'داشبورد',
    products:       'محصولات',
    brands:         'برندها',
    discounts:      'کدهای تخفیف',
    reviews:        'نظرات',
    settings:       'تنظیمات',
    backToSite:     'بازگشت به سایت',

    // Guard
    checkingAuth:   'در حال بررسی دسترسی...',
    forbidden:      'دسترسی غیرمجاز',
    forbiddenHint:  'شما به این بخش دسترسی ندارید. برای دسترسی، با مدیر سایت تماس بگیرید.',
    notLoggedIn:    'برای دسترسی باید وارد شوید.',
    goToLogin:      'ورود به حساب',
    goHome:         'بازگشت به خانه',

    // First admin
    claimTitle:     'شما اولین کاربر هستید',
    claimText:      'هیچ ادمینی در سیستم وجود ندارد. می‌توانید همین حالا خودتان را ادمین کنید.',
    claimButton:    'من را ادمین کن',
    claiming:       'در حال اعمال...',
    claimSuccess:   'شما ادمین شدید!',
    claimTaken:     'قبلاً ادمین دیگری ثبت شده. با او تماس بگیرید.',

    // Common actions
    new:            'جدید',
    create:         'ایجاد',
    edit:           'ویرایش',
    save:           'ذخیره',
    saving:         'در حال ذخیره...',
    cancel:         'انصراف',
    delete:         'حذف',
    deleting:       'در حال حذف...',
    confirm:        'تأیید',
    confirmDelete:  'آیا مطمئنید؟',
    confirmDeleteText: 'این عمل قابل بازگشت نیست.',
    search:         'جستجو...',
    filter:         'فیلتر',
    all:            'همه',
    pending:        'در انتظار تأیید',
    approved:       'تأییدشده',
    actions:        'عملیات',
    loading:        'در حال بارگذاری...',
    empty:          'موردی یافت نشد',
    noResults:      'نتیجه‌ای یافت نشد',
    backToList:     'بازگشت به لیست',
    created:        'با موفقیت ایجاد شد',
    updated:        'با موفقیت بروزرسانی شد',
    deleted:        'با موفقیت حذف شد',
    errorGeneric:   'خطایی رخ داد. دوباره تلاش کنید.',
    errorLoad:      'خطا در بارگذاری',

    // Dashboard
    totalProducts:  'کل محصولات',
    totalBrands:    'کل برندها',
    totalReviews:   'کل نظرات',
    pendingReviews: 'نظرات در انتظار',
    activeDiscounts:'کدهای فعال',
    totalDiscounts: 'کل کدها',
    quickActions:   'دسترسی سریع',
    recentReviews:  'آخرین نظرات',

    // Products
    productsTitle:  'مدیریت محصولات',
    productNew:     'محصول جدید',
    productEdit:    'ویرایش محصول',
    productFields: {
      slug:           'شناسه (slug)',
      nameFa:         'نام (فارسی)',
      nameEn:         'نام (انگلیسی)',
      brand:          'برند',
      descriptionFa:  'توضیحات (فارسی)',
      descriptionEn:  'توضیحات (انگلیسی)',
      price:          'قیمت (تومان)',
      discountPrice:  'قیمت با تخفیف',
      stock:          'موجودی',
      coverUrl:       'آدرس تصویر اصلی',
      gallery:        'گالری تصاویر',
      specs:          'مشخصات فنی',
      isFeatured:     'نمایش در محصولات ویژه',
      isActive:       'فعال',
      addGallery:     'افزودن تصویر',
      addSpec:        'افزودن مشخصه',
      specKey:        'کلید',
      specValue:      'مقدار',
      noBrand:        'بدون برند',
      selectBrand:    '— انتخاب برند —',
    },

    // Brands
    brandsTitle:    'مدیریت برندها',
    brandNew:       'برند جدید',
    brandEdit:      'ویرایش برند',
    brandFields: {
      slug:     'شناسه (slug)',
      nameFa:   'نام (فارسی)',
      nameEn:   'نام (انگلیسی)',
      logoUrl:  'آدرس لوگو',
      sortOrder:'ترتیب نمایش',
    },

    // Discounts
    discountsTitle: 'کدهای تخفیف',
    discountNew:    'کد تخفیف جدید',
    discountEdit:   'ویرایش کد تخفیف',
    discountFields: {
      code:           'کد',
      type:           'نوع',
      typePercent:    'درصدی',
      typeFixed:      'مبلغ ثابت',
      value:          'مقدار',
      minOrderAmount: 'حداقل مبلغ سفارش',
      maxDiscount:    'حداکثر تخفیف',
      startsAt:       'شروع',
      expiresAt:      'انقضا',
      usageLimit:     'محدودیت استفاده',
      usageCount:     'تعداد استفاده‌شده',
      isActive:       'فعال',
      descriptionFa:  'توضیح (فارسی)',
      descriptionEn:  'توضیح (انگلیسی)',
    },
    discountValuePercent: '{n}٪',
    discountValueFixed:   '{n} تومان',
    noExpiry:             'بدون انقضا',

    // Reviews
    reviewsTitle:      'مدیریت نظرات',
    reviewApprove:     'تأیید',
    reviewReject:      'رد',
    reviewApproved:    'تأیید شد',
    reviewRejected:    'رد شد',
    reviewBy:          'از طرف',
    reviewOnProduct:   'برای محصول',
    reviewRating:      'امتیاز',
    reviewComment:     'متن',
    reviewDate:        'تاریخ',
  },

  en: {
    panel:          'Admin panel',
    dashboard:      'Dashboard',
    products:       'Products',
    brands:         'Brands',
    discounts:      'Discounts',
    reviews:        'Reviews',
    settings:       'Settings',
    backToSite:     'Back to site',

    checkingAuth:   'Checking access...',
    forbidden:      'Access denied',
    forbiddenHint:  'You don\'t have access to this section. Contact the site admin.',
    notLoggedIn:    'You need to sign in to access this section.',
    goToLogin:      'Sign in',
    goHome:         'Back to home',

    claimTitle:     'You are the first user',
    claimText:      'There are no admins in the system. You can make yourself an admin now.',
    claimButton:    'Make me admin',
    claiming:       'Applying...',
    claimSuccess:   'You are now an admin!',
    claimTaken:     'Another admin already exists. Please contact them.',

    new:            'New',
    create:         'Create',
    edit:           'Edit',
    save:           'Save',
    saving:         'Saving...',
    cancel:         'Cancel',
    delete:         'Delete',
    deleting:       'Deleting...',
    confirm:        'Confirm',
    confirmDelete:  'Are you sure?',
    confirmDeleteText: 'This action cannot be undone.',
    search:         'Search...',
    filter:         'Filter',
    all:            'All',
    pending:        'Pending',
    approved:       'Approved',
    actions:        'Actions',
    loading:        'Loading...',
    empty:          'Nothing found',
    noResults:      'No results',
    backToList:     'Back to list',
    created:        'Created successfully',
    updated:        'Updated successfully',
    deleted:        'Deleted successfully',
    errorGeneric:   'Something went wrong. Please try again.',
    errorLoad:      'Failed to load',

    totalProducts:  'Total products',
    totalBrands:    'Total brands',
    totalReviews:   'Total reviews',
    pendingReviews: 'Pending reviews',
    activeDiscounts:'Active codes',
    totalDiscounts: 'Total codes',
    quickActions:   'Quick actions',
    recentReviews:  'Recent reviews',

    productsTitle:  'Products management',
    productNew:     'New product',
    productEdit:    'Edit product',
    productFields: {
      slug:           'Slug',
      nameFa:         'Name (Persian)',
      nameEn:         'Name (English)',
      brand:          'Brand',
      descriptionFa:  'Description (Persian)',
      descriptionEn:  'Description (English)',
      price:          'Price (IRR)',
      discountPrice:  'Discount price',
      stock:          'Stock',
      coverUrl:       'Cover image URL',
      gallery:        'Gallery',
      specs:          'Specifications',
      isFeatured:     'Show in featured',
      isActive:       'Active',
      addGallery:     'Add image',
      addSpec:        'Add spec',
      specKey:        'Key',
      specValue:      'Value',
      noBrand:        'No brand',
      selectBrand:    '— Select brand —',
    },

    brandsTitle:    'Brands management',
    brandNew:       'New brand',
    brandEdit:      'Edit brand',
    brandFields: {
      slug:     'Slug',
      nameFa:   'Name (Persian)',
      nameEn:   'Name (English)',
      logoUrl:  'Logo URL',
      sortOrder:'Sort order',
    },

    discountsTitle: 'Discount codes',
    discountNew:    'New discount code',
    discountEdit:   'Edit discount code',
    discountFields: {
      code:           'Code',
      type:           'Type',
      typePercent:    'Percent',
      typeFixed:      'Fixed amount',
      value:          'Value',
      minOrderAmount: 'Min order amount',
      maxDiscount:    'Max discount',
      startsAt:       'Starts at',
      expiresAt:      'Expires at',
      usageLimit:     'Usage limit',
      usageCount:     'Usage count',
      isActive:       'Active',
      descriptionFa:  'Description (Persian)',
      descriptionEn:  'Description (English)',
    },
    discountValuePercent: '{n}%',
    discountValueFixed:   '{n} IRR',
    noExpiry:             'No expiry',

    reviewsTitle:      'Reviews management',
    reviewApprove:     'Approve',
    reviewReject:      'Reject',
    reviewApproved:    'Approved',
    reviewRejected:    'Rejected',
    reviewBy:          'By',
    reviewOnProduct:   'On product',
    reviewRating:      'Rating',
    reviewComment:     'Comment',
    reviewDate:        'Date',
  },
};